### ISSUE TITLE
pngjs outdated causing deprecation warning

### ISSUE THREAD

**Issue by spasutto** [joshmarinacci/node-pureimage#161]
Thanks for the great work on this lib 👍 
Here is a minor concern about deprecation warning caused by outdated version of `pngjs` (current is 7.0.0, pureimage use 3.4.0)

### Expected Behaviour

1.No warning produced

### Actual Behaviour

1.Deprecation warning on `Buffer` constructor while converting to PNG (in PNG constructor) : 
```shell
$ node --trace-deprecation test.js
(node:16812) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.
from() methods instead.
    at showFlaggedDeprecation (node:buffer:197:11)
    at new Buffer (node:buffer:281:3)
    at new exports3.PNG (D:\dev\perso\igc2kmz\test.js:9966:59)
    at D:\dev\perso\igc2kmz\test.js:12162:25
    at new Promise (<anonymous>)
    at Object.encodePNGToStream2 (D:\dev\perso\igc2kmz\test.js:12158:16)
    at Object.<anonymous> (D:\dev\perso\igc2kmz\test.js:12422:8)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAAklEQVR4AewaftIAAADfSURBVO3BQQEAIACEMLziRtcaPNjOhUc0RlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlR
GVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURlRGVEZURl
RGVEZURlRGVEZURlRGVEZURlRGVEZUPpY6AkZW7OryAAAAAElFTkSuQmCC

```

### Steps To Reproduce

**Package used** : [base64-stream](https://www.npmjs.com/package/base64-stream)

**Typescript code :**
```typescript
import * as PImage from "pureimage"
import { Base64Encode } from 'base64-stream';

let img1 = PImage.make(100, 100, {  });
var ctx = img1.getContext('2d');
ctx.fillStyle = 'rgba(255,0,0, 0.5)';
ctx.fillRect(0,0,100,100);
let base64toout = new Base64Encode();
base64toout.pipe(process.stdout);
PImage.encodePNGToStream(img1, base64toout);
```
**Esbuild config :**
```js
import * as esbuild from 'esbuild'

await esbuild.build({
  platform: 'node',
  entryPoints: ["test.ts"],
  bundle: true,
  absWorkingDir: process.cwd(),
  outfile: 'test.js',
}).catch(() => process.exit(1))
```

### Platform
**OS:** Win10 Enterprise
**Node Version:** v18.14.2
**NPM Version:** 9.5.0
**PureImage Version:** 0.3.17

**Comment by joshmarinacci** [comment]
I've updated pngjs to 7.0.0 in the newest release: 0.4.0
